routes/web.php
<?php
use App\Http\Controllers\ProyectosController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Agregado por diapositiva
/*
Route::middleware('auth')->group(function () {
    Route::resource('projects', ProjectController::class);
});
*/

Route::resource('proyecto', ProyectosController::class);

app/Models/Proyectos.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Proyectos extends Model
{
    use HasFactory;

    // $fillable: evitamos asignación masiva.
    protected $fillable = ['nombre_completo', 'email', 'password', 'address', 'city'];
    // Asegúrate de listar todos los campos que deseas que sean asignables masivamente


    // método boot: mientras se esté creando un nuevo proyecto, guardamos el usuario id del momento.
    protected static function boot()
    {
        parent::boot();
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ProyectosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Proyectos;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\View\View;

class ProyectosController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //AGREGADO EN CLASE
        $proyectos = DB::table("proyectos")->get();
        return view("proyecto.index",["proyectos"=>$proyectos]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('proyecto.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        /*
        Proyectos::create($request->all());
        return redirect() -> route('proyecto.index') -> with('success', 'Post created successfully.');
        */

        // Crear una nueva instancia del modelo Proyectos.
        $proyecto = new Proyectos();

        // Asignar valores a los atributos del modelo.
        $proyecto->nombre_completo = $request->input('nombre_completo');
        $proyecto->email = $request->input('email');
        $proyecto->password = $request->input('password'); // Considera encriptar la contraseña antes de guardarla
        $proyecto->address = $request->input('address');
        $proyecto->city = $request->input('city');

        // Guardar el modelo en la base de datos.
        $proyecto->save();

        // Redireccionar a una ruta específica o retornar una vista con un mensaje de éxito.
        return redirect()->route('proyecto.index')->with('success', 'Proyecto creado con éxito.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Proyectos $proyectos)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $proyecto = Proyectos::find($id);
        return view('proyecto.edit', compact('proyecto'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nombre_completo' => 'required|max:255',
            'email' => 'required',
        ]);
        $proyecto = Proyectos::find($id);
        $proyecto->update($request->all());
        return redirect()->route('proyecto.index')
        ->with('success','El proyecto se ha actualizado correctamente');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $proyecto = Proyectos::find($id);
        $proyecto->delete();
        return redirect()->route('proyecto.index')
        ->with('success', 'el usuario ha sido eliminado correctamente');
    }
}

resources/views/proyecto/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">First proyect</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarText">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{{ route('proyecto.index') }}">Home</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
    <main>
        <div class="container">
            <section class="section register d-flex flex-column align-items-center justify-content-center">
                <div class="container">
                    <div class="row justify-content-center ">
                        <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center ">
                            <div class="card mt-5">
                                <div class="card-body">
                                    <div class="pt-4 pb-2">
                                        <h5 class="card-title text-center pb-0 fs-4">User register</h5>
                                    </div>
                                    <form class="row g-3 needs-validation" action="{{ route('proyecto.store') }}" method="post">
                                        @csrf <!-- Incluir el token CSRF -->
                                        <div class="col-md-12">
                                            <label for="inputNombreCompleto" class="form-label">Full name</label>
                                            <input type="text" class="form-control" id="inputNombreCompleto" name="nombre_completo">
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputEmail" class="form-label">Email</label>
                                            <input type="email" class="form-control" id="inputEmail" name="email">
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputPassword" class="form-label">Password</label>
                                            <input type="password" class="form-control" id="inputPassword" name="password">
                                        </div>
                                        <div class="col-12">
                                            <label for="inputAddress" class="form-label">Address</label>
                                            <input type="text" class="form-control" id="inputAddress" name="address">
                                        </div>
                                        <div class="col-md-12">
                                            <label for="inputCity" class="form-label">City</label>
                                            <input type="text" class="form-control" id="inputCity" name="city">
                                        </div>
                                        <div class="col-12">
                                            <button class="btn btn-primary w-100" type="submit">Create Account</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/proyecto/edit.blade.php
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
	<body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">First proyect</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarText">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{{ route('proyecto.index') }}">Home</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<h1 style="margin: 50px 100px">Update data</h1>
		<form action="{{ route('proyecto.update', $proyecto->id) }}" method="post" style="padding: 0px 100px">
            @csrf
            @method("put")
            <div class="col-md-6 form-group">
                <label for="nombre">Name</label>
                <input type="text" class="form-control" id="inputNombreCompleto" name="nombre_completo" value="{{ $proyecto->nombre_completo }}" required>
            </div>
            <div class="col-md-6 form-group mt-3">
                <label for="inputEmail" class="form-label">Email</label>
                <input type="email" class="form-control" id="inputEmail" name="email" value="{{ $proyecto->email }}" required>
            </div>
            <div class="col-md-6 mt-3">
                <label for="inputPassword" class="form-label">Password</label>
                <input type="password" class="form-control" id="inputPassword" name="password" value="{{ $proyecto->password }}" required>
            </div>
            <div class="col-6 mt-3">
                <label for="inputAddress" class="form-label">Address</label>
                <input type="text" class="form-control" id="inputAddress" name="address" placeholder="1234 Main St" value="{{ $proyecto->address }}" required>
            </div>
            <div class="col-md-6 mt-3">
                <label for="inputCity" class="form-label">City</label>
                <input type="text" class="form-control" id="inputCity" name="city" value="{{ $proyecto->city }}" required>
            </div>
            <button type="submit" class="btn mt-3 btn-primary">
                Update
            </button>
        </form>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	</body>
</html>

resources/views/proyecto/index.blade.php
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
	<body>
		<nav class="navbar navbar-expand-lg bg-body-tertiary">
			<div class="container-fluid">
				<a class="navbar-brand" href="#">First proyect</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarText">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="#">Home</a>
						</li>
					</ul>
					<span class="navbar-text">
						<a href="{{ route('proyecto.create') }}"><button type="button" class="btn btn-outline-primary">Registered users</button></a>
					</span>
				</div>
			</div>
		</nav>
		<h1 style="margin: 50px 100px">Registered users </h1>
		<div class="container">
			<table class="table align-middle mb-0 bg-white" >
				<thead class="bg-light">
					<tr>
					<th>Name</th>
					<th>Address</th>
					<th>Update</th>
					<th>State</th>
					<th>Actions</th>
					</tr>
				</thead>
				<tbody>
				@foreach ($proyectos as $proyecto)
					<tr>
						<td>
								<div class="ms-3">
									<p class="fw-bold mb-1">{{$proyecto->nombre_completo}}</p>
									<p class="text-muted mb-0">{{$proyecto->email}}</p>
								</div>
							</div>
						</td>
						<td>
							<p class="fw-normal mb-1">{{$proyecto->address}}</p>
							<p class="text-muted mb-0">{{$proyecto->city}}</p>
						</td>
						<td>{{$proyecto->updated_at}}</td>
						<td>
							<span class="badge text-bg-primary">Active</span>
						</td>
						<td>
							<a href="{{ route('proyecto.edit', $proyecto->id) }}"><button type="button" class="btn btn-primary btn-sm">Edit</button></a>
							<form action="{{ route('proyecto.destroy', $proyecto->id) }}" method="POST">
								@csrf
								@method('DELETE')
								<button type="button" class="btn btn-primary btn-sm" onclick ="return confirm">Eliminate</button>
							</form>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
		
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
	</body>
</html>